[package]
name = "mdr-service"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.7.1", features = ["trace", "cors"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
config = "0.15.26"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "migrate"] }
axum = { version = "0.8.9", features = ["macros"] }
serde = { version = "1.0.229", features = ["derive"] }
anyhow = "1.0.104"
serde_derive = "1.0.229"
uuid = { version = "1.26.1", features = ["v4", "serde"] }
http-body-util = "0.1.5"
serde_json = "1.0.151"
mime = "0.3.17"
