name: mdr

services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${MDR_DB_USER:-postgres}
      POSTGRES_DB: ${MDR_DB_DATABASE:-mdr}
      POSTGRES_PASSWORD: ${MDR_DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5