name: build & test

"on":
  push:
  pull_request:

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DATABASE_URL: "postgres://${{ DB_USER }}:${{ DB_PASSWORD }}@localhost/mdr"
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: $DB_USER
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_DB: mdr
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
      - name: Migrate database
        run: cargo sqlx migrate run
      - name: Build
        run: cargo build --verbose
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: diz-unimr/mdr-service
